// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {pkg} from '../models';
import {main} from '../models';

export function CreateProfileFromDefault(arg1:string,arg2:string,arg3:string,arg4:Array<string>):Promise<string>;

export function GetProfile(arg1:string):Promise<pkg.Profile>;

export function GetProfileFiles():Promise<Array<string>>;

export function GetProfiles():Promise<Array<pkg.Profile>>;

export function GetProfilesStatus():Promise<main.ProfilesStatus>;

export function GetXplane():Promise<Array<string>>;

export function GetXplaneDataref(arg1:string):Promise<string>;

export function SaveProfileByIndex(arg1:number,arg2:pkg.Profile):Promise<void>;

export function SelectProfilesFolder():Promise<void>;
